apiVersion: v1
kind: Namespace
metadata:
  name: ingress-nginx
  labels:
    name: ingress-nginx
---
# apiVersion: v1
# kind: Namespace
# metadata:
#   name: monitoring
#   labels:
#     name: monitoring
    