---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:

  # Monitoring
  - ../../../vendor/katalog/monitoring/prometheus-operator
  - ../../../vendor/katalog/monitoring/prometheus-operated
  - ../../../vendor/katalog/monitoring/prometheus-adapter
  - ../../../vendor/katalog/monitoring/grafana
  - ../../../vendor/katalog/monitoring/kube-state-metrics
  - ../../../vendor/katalog/monitoring/kube-proxy-metrics
  - ../../../vendor/katalog/monitoring/kubeadm-sm
  - ../../../vendor/katalog/monitoring/node-exporter
  - ../../../vendor/katalog/monitoring/alertmanager-operated