---
- name: Copy configuration file
  copy:
    content: '{{ headscale_config | to_yaml }}'
    dest: '{{ headscale_config_dir }}/config.yaml'
    owner: '{{ headscale_user_uid }}'
    group: '{{ headscale_user_gid }}'
    mode: 0600
  notify: reload headscale

- name: Copy ACL policies file
  copy:
    content: '{{ headscale_acl | to_yaml }}'
    dest: '{{ headscale_config_dir }}/acl.yaml'
    owner: '{{ headscale_user_uid }}'
    group: '{{ headscale_user_gid }}'
    mode: 0600
  notify: reload headscale

- name: Ensure predefined users exist
  command:
    cmd: 'headscale users create {{ item }}'
  loop: '{{ headscale_users }}'
  register: user_created
  changed_when: '"User created" in user_created.stdout'
