---
version: "2.1"
services:
  wireguard:
    image: lscr.io/linuxserver/wireguard
    container_name: wireguard
    cap_add:
      - NET_ADMIN
      - SYS_MODULE
    environment:
      - PUID=1001
      - PGID=100
      - TZ=Europe/Rome
      - SERVERURL=<YOUR SERVER URL> #optional
      - SERVERPORT=51820
      - PEERS=client,iphone #change to match how many devies you want to use Wireguard on
      - PEERDNS=192.168.0.2,8.8.8.8
      - INTERNAL_SUBNET=10.13.13.0 #optional
      - ALLOWEDIPS=0.0.0.0/0 #optional
    volumes:
      - ~/docker/utility/wireguard/config:/config
      - /lib/modules:/lib/modules #do not change
    ports:
      - 51820:51820/udp
    restart: unless-stopped