---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  # Logging
  - ../../../vendor/katalog/logging/opensearch-single
  - ../../../vendor/katalog/logging/opensearch-dashboards
  - ../../../vendor/katalog/logging/logging-operator
  - ../../../vendor/katalog/logging/logging-operated
  - ../../../vendor/katalog/logging/configs
  - ../../../vendor/katalog/logging/minio-ha

patchesStrategicMerge:
  - patches/infra-scheduling.yml
  - patches/minio-replicas.yml
  - patches/resize-pvc-opensearch.yml
  - patches/resize-pvc-minio.yml